version: '3.6'
services:
  backend:
    build:
      context: .
    working_dir: /app
    ports:
      - '8080:8000'
    volumes:
      - '.:/app'
      - /app/vendor
      - /app/node_modules
    command: php artisan serve --host 0.0.0.0
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3308:3306'
    volumes:
      - ./storage/dbdata/:/var/lib/mysql